### ISSUE TITLE
'musixmatch' is not in the npm registry

### ISSUE THREAD

**Issue by Kuchiriel** [pilu/musixmatch-node#1]
> npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/musixmatch
> npm ERR! 404 
> npm ERR! 404  'musixmatch' is not in the npm registry.

**Comment by gravityblast** [comment]
hi @Kuchiriel, I removed the npm package because I wasn't updating it anymore, and someone else wanted to publish a package with the same name. I'll remove that from the README

**Comment by Kuchiriel** [comment]
Okay @pilu, thanks for the reply.
